### ISSUE TITLE
Cannot add or edit calendars via UI

### ISSUE THREAD

**Issue by bjagg** [Jasig/CalendarPortlet#81]
In both our development version (v5.1.2) and the most recent "vanilla" version of uPortal and uPortal-start (v5.2.3), I can't add or edit calendars in the Calendar portlet (v2.6.0).

Steps to reproduce after deploying locally with uPortal-start:

1. log in as staff or student 
2. click on Calendar portlet name to maximize portlet and reveal Preferences link 
3. click on Preferences 
4. click on + Add a calendar 
5. fill in Calendar name and Calendar URL 
6. click on "Save calendar" button

No new calendar.

Does this happen for you? Could you see if others report the same behavior? It's easy to check if you have uPortal 5 running.

After much debugging I think I know what the problem is but I don't know how to resolve it.

On the "Edit calendar" page (editCalendarUrl.jsp), after entering a Calendar name and Calendar URL, when I click the "Save calendar" button, it's supposed to redirect to Action "editUrl" but it's not getting there because the request looks like this:

http://localhost:8080/uPortal/f/welcome/p/calendar.u25l1n13/max/action.uP?_csrf=403fcb62-9a79-4a32-8874-3a09a1af64f0&amp;pP_action=editUrl

The _csrf parameter is encoding the ampersand as "&amp;" instead of an "&" before the next parameter, "pP_action=editUrl" so in the browser (Chrome), the Query String Parameters list ends up looking like:

_csrf: 403fcb62-9a79-4a32-8874-3a09a1af64f0 
amp;pP_action: editUrll

It looks like the "&amp;" isn't getting decoded back to "&" so the second query parameter ends up being "&amp;pP_action" which is likely not being recognized by Spring Portlet or uPortal or whatever processes "pP_action" as an action request.

I've put debug statements in EditUserHttpICalController on the showHttpCalendarForm and updateHttpCalendar methods and it never gets to the updateHttpCalendar method, suggesting that uPortal or the CalendarPortlet isn't decoding the "&amp;" properly. I noticed that this is using Spring Web MVC 3.1.3.RELEASE which is pretty old.

I tried it with uPortal 5.2.3 and CalendarPortlet 2.6.0 using uPortal-start (./gradlew portalInit, ./gradlew tomcatDeploy, ./gradlew tomcatStart) as both admin and staff. Click on Calendar name in portlet header to expand to full screen and display Preferences (and Administration for admin user).

**Comment by laurenra7** [comment]
This is the same [issue reported by Julien Gribonvald](https://groups.google.com/a/apereo.org/forum/#!topic/uportal-dev/dZ7P86jlWR0). The [fix suggested by Drew](https://groups.google.com/a/apereo.org/d/msg/uportal-dev/dZ7P86jlWR0/O1MR06VVCgAJ) is to add **escapeXml="false"** in the **<portlet:actionURL>** tag. For example:

`<form:form name="calendar" cssClass="form-horizontal" commandName="userHttpIcalCalendarForm" action="${postUrl}">`

I'll create a pull request when I've got this resolved and tested.
